apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-staging

resources:
- ../../base
- namespace.yaml

patches:
- patch: |-
    - op: replace
      path: /data/APP_ENVIRONMENT
      value: staging
  target:
    kind: ConfigMap
    name: todo-app-config
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: FORWARD_EXTERNAL_MESSAGES
        value: "false"
  target:
    kind: Deployment
    name: broadcaster-deployment

images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/my-dwk-gke/my-repository/dwk-environments-broadcaster
  newTag: main-e8d7112219daaddb77de28e201fa03ae700542af
- name: PROJECT/TODO-APP
  newName: europe-north1-docker.pkg.dev/my-dwk-gke/my-repository/dwk-environments
  newTag: main-e8d7112219daaddb77de28e201fa03ae700542af
- name: PROJECT/todo-backend
  newName: europe-north1-docker.pkg.dev/my-dwk-gke/my-repository/dwk-environments-backend
  newTag: main-e8d7112219daaddb77de28e201fa03ae700542af
