apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
- ../../base
- namespace.yaml
- manifests/postgres-backup-cronjob.yaml

images:
- name: PROJECT/BROADCASTER
  newName: europe-north1-docker.pkg.dev/my-dwk-gke/my-repository/dwk-environments-broadcaster
  newTag: v0.4
- name: PROJECT/TODO-APP
  newName: europe-north1-docker.pkg.dev/my-dwk-gke/my-repository/dwk-environments
  newTag: v0.4
- name: PROJECT/todo-backend
  newName: europe-north1-docker.pkg.dev/my-dwk-gke/my-repository/dwk-environments-backend
  newTag: v0.4
