apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: project
data:
  APP_ENVIRONMENT: production
  APP_PORT: "3000"
  BACKEND_PORT: "3001"
  BROADCASTER_PORT: "3002"
  TODO_BACKEND_URL: http://todo-backend-svc:3001
  NATS_URL: nats://my-nats.nats.svc.cluster.local:4222
  IMAGES_DIR: /usr/src/app/images
  IMAGE_SOURCE_URL: https://picsum.photos/200
  CACHE_DURATION_MS: "600000"
  MAX_TODO_LENGTH: "140"
  POSTGRES_HOST: postgres-svc
  POSTGRES_DB: todos
  POSTGRES_USER: todos_user
